language: java
before_install: sudo pip install codecov
script: mvn -Pjacoco -Dmaven.javadoc.skip=true -q verify
jdk:
  - openjdk6
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
git:
  depth: 3
after_success: codecov
